### PR TITLE
use new parent pom and repo

### PR DESCRIPTION
**Pull request by wow-such-code**

### CODE REVIEW

**Review by Steffengreiner — APPROVED** [review]
LGTM! Nice usage of properties to keep the vaadin 7 version.

**Review by KochTobi — CHANGES_REQUESTED** [review]
Looks good but the Travis build fails. This should not be the case.

**Comment by sven1103** [comment]
closing due to stalling build

**Review by KochTobi — COMMENTED** [review]
build ran through

**Pull request closed without merging**
